### ISSUE TITLE
Why do you live in France?

### ISSUE THREAD

**Issue by SamVerschueren** [jfmengels/ama#1]

**Comment by jfmengels** [comment]
I currently live in France, because I pretty much always lived here. My parents moved here when I was only 6 months (not worth mentioning that they didn't ask me for my opinion on the matter), as my dad found a job in Paris, and we stayed there.

I have since then lived abroad during my studies and for internships (Netherlands, Quebec and San Francisco), but went back to France every time until now.

And for "completeness' sake", I was born in the Netherlands and am therefore dutch. I have not requested the french citizenship.

Thank you for the first question in my AMA :D
