### ISSUE TITLE
Are you ever afraid of being over-invested into Elm?

### ISSUE THREAD

**Issue by 3v0k4** [jfmengels/ama#12]
I'm thinking of opportunity cost (could learn other technologies) and Elm potentially becoming less and less relevant.

**Comment by jfmengels** [comment]
In terms of opportunity cost, I think I'm losing more because of my investment into making tools (and mostly a single niche tool) than about being invested in Elm. Instead of working on `elm-review`, I could be learning how to improve my CSS skills or my skill to build complex architectures with hundreds of servers. In other words, I could spend that time learning things that make me more marketable and better at my current or future jobs. Not that I'm not learning things when building my tools, but it's definitely not the *best* investment.

As you say, I could learn also spend that time learning other technologies that are interesting or marketable and will get me more jobs. I do wish I could/would spend more time learning new things, as I definitely feel like I'm not expanding my mind enough to new ideas.

As you probably experienced, Elm is still a good language to learn ways to make good and simple code in a way that will actively change how you write code in other languages. So I'm super happy to be using Elm. I have probably learned *nearly* all that is useful, but since it's an awesome language I'll keep using it :slightly_smiling_face: 

As to the part of potentially becoming less and less relevant, sure that could happen. I'm not too afraid of the language dying, since it still works really well for the people who are using it. What I'm most afraid of, because that will likely happen earlier, is that I change jobs and have trouble finding an Elm job. At the moment, I only feel like going to other companies if they use Elm, because that's what I feel like doing and that's what I'm good at.

But whether they use Elm or not is only one part of the requirements for me for a company. I'd need the company to be timezone-compatible with me, be in an industry I don't despise, have a company culture that I can appreciate, pays well enough, etc. So I do feel like I'm limited in my choices, and that doesn't feel nice. But others probably feel the same, if for instance they want to be a game dev at a company using Rust but their favorite companies all use C++.

I am probably a little bit afraid but more as a fear of missing out rather than a fear of Elm becoming irrelevant, though the fear of not being able to find a place where I can work in a fulfilling role is present.

I do acknowledge that Elm is unlikely to exist and remain the greatest available option for the entirety of my career, so I'll probably jump ship at some point. I always think that if I ever do jump ship, I'll probably create a new linter in that community :sweat_smile:

**Comment by 3v0k4** [comment]
Thanks for going so deep with the answer 🙏

I guess this belongs to the neverending generalist vs specialist discussion. Though, I do think there's one way to slash that: focusing on an obsession instead.

I don't want to put words in your mouth, but it looks like yours could be: "helping devs find mistakes before their users find them."  Currently, you are solving it with `elm-review`, but your experience and recognition give you a seat at the table of anyone interested in that.

> I'll probably create a new linter in that community

Kickass move (that a generalist cannot play) 🤘

**Comment by jfmengels** [comment]
Yeah, finding problems and improving the general experience when programming is one of the things I like working on. Mostly because I get frustrated with them myself or want help (my work is usually self-centered as a start :smile: ).

> your experience and recognition give you a seat at the table of anyone interested in that

Right, but whether that will get me a job and/or put food on the table is an entirely different question to "can I do OSS in that language?".
