### ISSUE TITLE
How did you get started with open source?

### ISSUE THREAD

**Issue by sindresorhus** [jfmengels/ama#8]

**Comment by jfmengels** [comment]
Mostly already answered in https://github.com/jfmengels/ama/issues/2#issuecomment-242563713.

I started working at the beginning of this year on documentations for lodash/fp, because I thought it was pretty cool but the docs for it were very bad. I started following the Lodash issues (man are there many, and man do they close fast), which was a pretty intense and interesting introduction to open source, while working on those docs. The docs didn't end up good enough, so they were accepted but quickly removed.

A few weeks later, a project I had heard about (_probably_ also tried it) named [AVA](https://github.com/avajs/ava) created an [eslint plugin repo](https://github.com/avajs/eslint-plugin-ava) where they requested help a few rules. As I had looked at ESLint a little bit before, I thought I'd give it a try. Since they were simple enough, I ended up writing them all, and then submitting a PR.

Continuing on with my experience with ASTs and ESLint, I created `eslint-plugin-lodash-fp`, then got invited in the Lodash organization for my involvement in the project (docs, eslint plugin, Gitter/issues support, ...).
From then on, I started creating quite a few tools to help me write other tools in a simpler way, got involved in plenty of ESLint plugins, and eventually got invited to the AVA team.

A bit more than just the start, but that has been my 6-7 month journey into open source.
