### ISSUE TITLE
What thing are you irrationally afraid of?

### ISSUE THREAD

**Issue by Haroenv** [jfmengels/ama#9]

**Comment by jfmengels** [comment]
I really don't like spiders. It goes better with time, as I am now able to kill or capture and throw them out, but I still to prefer to ask someone else to do it for me :D. It's not to the point anymore that I would call it a fear though.

I don't think there's much else I am irrationally afraid of... :question:

**Comment by Haroenv** [comment]
Spiders are a classic

**Comment by jfmengels** [comment]
I tried to be original on this front but my parents wouldn't let me :disappointed:

**Comment by jfmengels** [comment]
Oh! There's actually an other one!

I used to be very afraid of stepping on the last step of my stairs at home. The stairs were open (meaning you could see from the other side and put your arm in between two steps), and on the last step, you couldn't see anything from the other side, and every time I jumped over it. The reason? I was scared that the clown from the movie/novel `It` (Stephen King) would catch my leg and rip it off. All because of one [awful scene in the movie](https://www.youtube.com/watch?v=OPdDdC4go6c)...

**Comment by Haroenv** [comment]
That's a cute fear!
